@baseUrl = http://localhost:5000
@urlPath = api/v1

####
POST {{baseUrl}}/{{urlPath}}/post/comment
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "userTo":"63baeea9d2525c544e7e3cd2",
    "postId":"63d69df93e96772942fb0d66",
    "profilePicture":"https://res.cloudinary.com/dol6oy4pb/image/upload/v1673195178/63baeea9d2525c544e7e3cd2",
    "comment":"this is the secod comment"
}

####
GET {{baseUrl}}/{{urlPath}}/post/comments/names/63d69df93e96772942fb0d66
Content-Type: application/json
Accept: application/json
withCredentials: true

####
GET {{baseUrl}}/{{urlPath}}/post/single/comment/63d69df93e96772942fb0d66/63e7dd9262b35e690c333839
Content-Type: application/json
Accept: application/json
withCredentials: true

####
GET {{baseUrl}}/{{urlPath}}/post/comments/63d69df93e96772942fb0d66
Content-Type: application/json
Accept: application/json
withCredentials: true
