@baseUrl = http://localhost:5000
@urlPath = api/v1

####
PUT {{baseUrl}}/{{urlPath}}/user/follow/6436f9d14337cece13f23602
Content-Type: application/json
Accept: application/json
withCredentials: true

{
}


# followingId/currentUserId
###
PUT {{baseUrl}}/{{urlPath}}/user/unfollow/6436f9d14337cece13f23602/6436f9df4337cece13f23609
Content-Type: application/json
Accept: application/json
withCredentials: true

{}
