@baseUrl = http://localhost:5000
@urlPath = api/v1

####
POST {{baseUrl}}/{{urlPath}}/post/reaction
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "userTo":"63baeea9d2525c544e7e3cd2",
    "postId":"63d69df93e96772942fb0d66",
    "type":"love",
    "previousReaction":"",
    "postReactions":{"like":0,"love":1,"happy":0,"sad":0,"wow":0,"angry":0},
    "profilePicture":"https://res.cloudinary.com/dol6oy4pb/image/upload/v1673195178/63baeea9d2525c544e7e3cd2"
}

####
GET {{baseUrl}}/{{urlPath}}/post/all/1
Content-Type: application/json
Accept: application/json
withCredentials: true

####
DELETE {{baseUrl}}/{{urlPath}}/post/reaction/63d69df93e96772942fb0d66/love/{"like":0,"love":0,"happy":0,"sad":0,"wow":0,"angry":0}
Content-Type: application/json
Accept: application/json
withCredentials: true

{}
